"""add notification channel

Revision ID: 3b74f43da6c1
Revises: 29748aa4dbf8
Create Date: 2026-09-23 19:47:44.071460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b74f43da6c1'
down_revision: Union[str, None] = '29748aa4dbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_channel', sa.String(length=20), server_default='both', nullable=False), schema='task_notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'notification_channel', schema='task_notification')
    # ### end Alembic commands ###



